
spring:
  datasource:
    url: jdbc:h2:mem:bfhl;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true 

app:
  name: "John Doe"           # <-- change
  regNo: "REG12347"          # <-- change
  email: "john@example.com"  # <-- change
  baseUrl: "https://bfhldevapigw.healthrx.co.in"
  # If API requires TLS settings/corporate proxy, configure WebClient accordingly.

logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
